//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        public int id { get; set; }
        public string names { get; set; }
        public string category { get; set; }
        public Nullable<int> userid { get; set; }
        public string prod { get; set; }
        public int years { get; set; }
    
        public virtual user user { get; set; }
    }
}
